### ISSUE TITLE
The ControlNet support is broken

### ISSUE THREAD

**Issue by InformEthics** [raysers/Mflux-ComfyUI#10]
When using controlNet through the ControlNet Loader an image input is required on the Quick MFlux generation,  otherwise there is error : 'NoneType' object has no attribute 'read'"

img2img and ControlNet are 2 different features and the possibility should be given to use them separately. Also there is no way to pass the controlnet-strength variable to MFlux

I propose to integrate the controlnet-strength slider into ControlNet Loader and give the possibility to pass Images from standard ComfyUI Image Loader node to ControlNet Loader! Or make the MFlux Load Image node more universal and integrate the ControlNet-Strength Slider into it

**Comment by raysers** [comment]
@InformEthics Thank you for your feedback. In the early versions of this plugin, ControlNet was indeed designed as an integrated feature, as you mentioned. However, after adding the image-to-image functionality, I separated the image and strength parameters into standalone nodes, resulting in the current implementation.

What you mentioned about ControlNet and img2img being different features is true—they should ideally be handled independently. In conventional workflows, ControlNet and img2img are indeed distinct functionalities. However, in mflux, the img2img mechanism differs from the mainstream img2img denoising principle. It also uses strength, which overlaps with mflux ControlNet. This overlap was the main reason behind my redesign—to avoid redundant code. My recent tests have also confirmed this. When running the mflux ControlNet workflow, the MFlux Load Image node’s strength parameter affects ControlNet by providing the ControlNet_strength value. As for the 'NoneType' object has no attribute 'read' error, while it does occur, it shouldn’t impact usability.

Additionally, using the standard ComfyUI Image Loader to provide images for mflux is currently not feasible. This is because the node passes PyTorch tensors, which need to be converted into the MLX architecture’s required data format to work correctly. Implementing this would require in-depth research.

I deeply apologize if this has caused you any inconvenience. However, I am still actively researching real-time preview functionality. As long as the current ControlNet implementation does not affect usability, I don’t plan to make adjustments to it for the time being. Allow me to explain the priority of "real-time preview": it is the final component of mflux 0.4.X. Completing this feature is essential for fully porting mflux 0.4.X to ComfyUI. I am committed to this because we are already significantly behind the official mflux development. While I am still working on mflux 0.4.X, the official team is already advancing to mflux 0.5.0.

I can also share some good news about mflux 0.5.0—it may support more popular models and include Flux.1 Tools, which also feature ControlNet. Once I complete mflux 0.4.X and begin porting mflux 0.5.0, I will adjust my node design according to the new official features. This means there might still be a refactor of the ControlNet component, depending on what the official mflux 0.5.0 introduces.

**Comment by InformEthics** [comment]
Hi, as I said - ControlNet functionality was broken for me. 
There are 2 different parameters passed to Mflux: init_image_strength and controlnet_strength, they should be handled separately. As I know Mflux cannot handle img2img and ControlNet input at the same time. So rather IMG2IMG Loader should be loaded or ControlNet.
I created a fork from your repository and made  a new ControlNet Loader Node that is working for me. Please check it out!

https://github.com/InformEthics/ComfyMFlux

**Comment by InformEthics** [comment]
<img width="1634" alt="Screenshot 2024-11-26 at 12 32 54 AM" src="https://github.com/user-attachments/assets/22aa7eff-1a36-4a0c-aac5-9600d065b001">

**Comment by InformEthics** [comment]
<img width="1621" alt="ControlNet" src="https://github.com/user-attachments/assets/4943c77f-f08e-45fe-b96a-2295602f1885">

**Comment by InformEthics** [comment]
hey guys, please don't take it personally and take a deep breath, it is my first time I upload something on GitHub, so please be patient - I tried first to fork this project in the same original repository, but I did not found how to do it, so in the end I just uploaded it on my account and mentioned that it is a fork... my intention was to show to you the changes that I made, it is not my new project, when I find out how to do pull request, I will do it!
I have really no intention and no interest of calling it my or yours or whose ever, I was thinking the project is open source and I called your attention to the fact that ControlNet for me is not working and I explained the issue, you ignored it saying that it is not the priority and it does not affect usability, but again - for me it still did not work correctly and once I looked into code, after your response, I saw that it is not clean, how img2img and ControlNet is handled. Also it is just than I realized that I need to check if Mflux can handle img2img and ControlNet at the same time! When I started researching, I saw that in the Mflux examples it is never being called together. I was not aware of it before neither until I started debugging your plug-in. 

So what I saw is basically you are using the MFluxImageLoader to pass on the strength variable to Mflux generator, but somehow the image  is passed as well  in the same time to img2img in Mflux, it created lot of different strange error codes and even when I did the workflow that you showed as example, ControlNet did not work for me - it had no effect on the final image. That's why I changed the code and uploaded it to GitHub, to show it to you in hope that you can see that there was a problem before and it got solved now.

I would love if the changes that I made could be implemented back into your plugin, only thing that makes me considering leaving it a fork is the fact that I like to keep it minimalistic in one file instead of 3 and having all the plugins all together in one folder instead of in 2 different subfolders. This might be question of taste, but as your project is open source I feel free to adopt it to my taste and needs.

As usual I have no responsibility about other adult's emotions or reactions and as usual they come from a space of misunderstanding and projections, but I would feel sorry or lets say find that its a pity  if you will not release your update because of the emotions that my actions triggered in you. 

I dont agree that my actions kill the spirit of open source, in contrary - I made your code work better than before and made it public, mentioning that it is a fork of your original project, newer mentioning that it is mine or asking for something.

I will try to fork it directly so it is mentioned inside the GitHub... I will get into it tomorrow, for now I am too tired and need some sleep :)

**Comment by raysers** [comment]
> I was opening the same PR. I’m sorry about your mood; I deeply understand it.

Hi, @azrahello, my friend, I think you may have misunderstood me. Perhaps you didn’t grasp how I felt. Forking is something any developer would welcome, as every forker is a potential contributor to the project, and any reasonable PR request is a valuable boost to the project’s growth.

What I dislike is simply taking most of my code and releasing it as a new project. Yesterday, @InformEthics' behavior felt like it fell into this category. What’s worse, after releasing it, he still came here claiming it was a fork. This left me feeling deceived. Since you weren’t involved, you might not fully understand how I feel. If just piecing together others’ code and making minor modifications could qualify as creating a new project, then ComfyUI would have far more than its current 1600+ plugins—probably ten or even a hundred times that number.

The fact that there are only 1600+ plugins shows that the community atmosphere is still excellent, as most people wouldn’t stoop to doing something so disrespectful. Unfortunately, yesterday, I thought I had encountered such a bad case, which made me very angry. Of course, now that InformEthics has clarified the situation, my speculation from yesterday seems rash in hindsight.

**Comment by raysers** [comment]
> hey guys, please don't take it personally and take a deep breath, it is my first time I upload something on GitHub, so please be patient - I tried first to fork this project in the same original repository, but I did not found how to do it, so in the end I just uploaded it on my account and mentioned that it is a fork... my intention was to show to you the changes that I made, it is not my new project, when I find out how to do pull request, I will do it! I have really no intention and no interest of calling it my or yours or whose ever, I was thinking the project is open source and I called your attention to the fact that ControlNet for me is not working and I explained the issue, you ignored it saying that it is not the priority and it does not affect usability, but again - for me it still did not work correctly and once I looked into code, after your response, I saw that it is not clean, how img2img and ControlNet is handled. Also it is just than I realized that I need to check if Mflux can handle img2img and ControlNet at the same time! When I started researching, I saw that in the Mflux examples it is never being called together. I was not aware of it before neither until I started debugging your plug-in.
> 
> So what I saw is basically you are using the MFluxImageLoader to pass on the strength variable to Mflux generator, but somehow the image is passed as well in the same time to img2img in Mflux, it created lot of different strange error codes and even when I did the workflow that you showed as example, ControlNet did not work for me - it had no effect on the final image. That's why I changed the code and uploaded it to GitHub, to show it to you in hope that you can see that there was a problem before and it got solved now.
> 
> I would love if the changes that I made could be implemented back into your plugin, only thing that makes me considering leaving it a fork is the fact that I like to keep it minimalistic in one file instead of 3 and having all the plugins all together in one folder instead of in 2 different subfolders. This might be question of taste, but as your project is open source I feel free to adopt it to my taste and needs.
> 
> As usual I have no responsibility about other adult's emotions or reactions and as usual they come from a space of misunderstanding and projections, but I would feel sorry or lets say find that its a pity if you will not release your update because of the emotions that my actions triggered in you.
> 
> I dont agree that my actions kill the spirit of open source, in contrary - I made your code work better than before and made it public, mentioning that it is a fork of your original project, newer mentioning that it is mine or asking for something.
> 
> I will try to fork it directly so it is mentioned inside the GitHub... I will get into it tomorrow, for now I am too tired and need some sleep :)



> hey guys, please don't take it personally and take a deep breath, it is my first time I upload something on GitHub, so please be patient - I tried first to fork this project in the same original repository, but I did not found how to do it, so in the end I just uploaded it on my account and mentioned that it is a fork... my intention was to show to you the changes that I made, it is not my new project, when I find out how to do pull request, I will do it! I have really no intention and no interest of calling it my or yours or whose ever, I was thinking the project is open source and I called your attention to the fact that ControlNet for me is not working and I explained the issue, you ignored it saying that it is not the priority and it does not affect usability, but again - for me it still did not work correctly and once I looked into code, after your response, I saw that it is not clean, how img2img and ControlNet is handled. Also it is just than I realized that I need to check if Mflux can handle img2img and ControlNet at the same time! When I started researching, I saw that in the Mflux examples it is never being called together. I was not aware of it before neither until I started debugging your plug-in.
> 
> So what I saw is basically you are using the MFluxImageLoader to pass on the strength variable to Mflux generator, but somehow the image is passed as well in the same time to img2img in Mflux, it created lot of different strange error codes and even when I did the workflow that you showed as example, ControlNet did not work for me - it had no effect on the final image. That's why I changed the code and uploaded it to GitHub, to show it to you in hope that you can see that there was a problem before and it got solved now.
> 
> I would love if the changes that I made could be implemented back into your plugin, only thing that makes me considering leaving it a fork is the fact that I like to keep it minimalistic in one file instead of 3 and having all the plugins all together in one folder instead of in 2 different subfolders. This might be question of taste, but as your project is open source I feel free to adopt it to my taste and needs.
> 
> As usual I have no responsibility about other adult's emotions or reactions and as usual they come from a space of misunderstanding and projections, but I would feel sorry or lets say find that its a pity if you will not release your update because of the emotions that my actions triggered in you.
> 
> I dont agree that my actions kill the spirit of open source, in contrary - I made your code work better than before and made it public, mentioning that it is a fork of your original project, newer mentioning that it is mine or asking for something.
> 
> I will try to fork it directly so it is mentioned inside the GitHub... I will get into it tomorrow, for now I am too tired and need some sleep :)

@InformEthics Since this was a misunderstanding, it’s good that everything has been clarified. Yesterday, in a fit of anger, I made some reckless assumptions about your actions, and for that, I apologize. I’m still not very familiar with GitHub, so I consider myself a beginner. Although I registered in 2018, I was mostly just passing through until June of this year, when I started exploring ComfyUI. In August, after noticing a slowdown following an update, I came to GitHub to ask the ComfyUI team about it. That’s when I decided to stay. So, in essence, I’m still a complete novice here.

Yesterday, I judged your actions as undermining the spirit of open source, but that was based on my misunderstanding. I believe that if the hard work of project creators ends up as mere copy-and-paste material for others, is that fair to the creators? Would they still be willing to open-source their work in the future? That’s why I thought such actions—specifically releasing a project directly using someone else’s code—essentially undermine the spirit of open source.

As a novice with no connections, if I encounter unfair treatment, I can only speak up for myself. That’s why I boldly voiced my dissatisfaction. This might be due to my lack of understanding of GitHub’s culture; perhaps the environment here is much better than I imagined.

Of course, what matters most is that you’ve clarified everything in the end. This experience has become a memorable one for me on GitHub. Moving forward, I may not update my project any further, so you can keep yours. Perhaps I’m better suited to being a user rather than a developer, as there are so many frustrating issues to deal with. Ultimately, I value copyright, and this experience has made me realize that open source may not be a good fit for me. My next steps will likely focus on studying the practicality of this plugin from a user’s perspective, specifically exploring its role in improving workflows.

**Comment by 135kp** [comment]
I am currently a professional product manager, and I used to be an IOS developer. If this project needs my participation, I can join in the relevant areas. Let's each focus on our own strengths, Mac users desperately need this plugin, which greatly improves speed. And if this plugin is completed perfectly, it will have a historic impact on the Mac computer world. @raysers Please continue with the development and make contributions to MLX. @InformEthics is also an excellent developer; let's all participate together. The more people from the community, the faster the progress. It's normal to encounter some friction at the beginning, let's all work hard together to perfect this MLX.

**Comment by InformEthics** [comment]
@raysers thanks to your project I learned how the ComfyUI nodes work, I am very thankful for it and I appreciate it a lot! I don't want to start a new Plug-In project wich is as you said mostly your code with some of my improvements and simplifications.... 
So please kindly accept my apologies - if I hurt your feelings, it was not my intention and today I will try to find the time to correct it and to upload it as a fork

I am rather interested in working together as a team having the common interest to make the project advance. I can also contribute helping implementing or testing new features. You said, we are behind the Mflux reseases implementing new features - please can you give a kind of a roadmap of implementing new features? 

Also I propose to make a discord channel for this project, so we can have more direct communication. Again, I would like you to stay the main project leader and I dont wont you to overtake this role, please forgive me any kind of impression that it was my intention.

**Comment by raysers** [comment]
Hello everyone, I am a bit busy today and can only use my mobile phone. Please wait a moment. I will reply to you one by one when I am free. Please forgive me.

**Comment by raysers** [comment]
> I am currently a professional product manager, and I used to be an IOS developer. If this project needs my participation, I can join in the relevant areas. Let's each focus on our own strengths, Mac users desperately need this plugin, which greatly improves speed. And if this plugin is completed perfectly, it will have a historic impact on the Mac computer world. @raysers Please continue with the development and make contributions to MLX. @InformEthics is also an excellent developer; let's all participate together. The more people from the community, the faster the progress. It's normal to encounter some friction at the beginning, let's all work hard together to perfect this MLX.

Thank you, @135kp. Your words are truly sincere, and I deeply appreciate the high level of importance you place on this project. While your mention of a "historic impact" might be an overstatement, I do believe that for mflux, ComfyUI is absolutely worth being regarded as a strategic focus for study. Unfortunately, the official team still hasn’t had the time to delve into it. However, from a user’s perspective, we can learn, grow, and progress together. We may not necessarily have the ability to achieve such a "historic impact," but having people who are willing to try, research, collaborate, and share together is truly a wonderful feeling.

I have always remembered your vision—it is truly a beautiful one. For the sake of this vision, we can take the first step together. So, let’s start from here!

**Comment by raysers** [comment]
> @raysers thanks to your project I learned how the ComfyUI nodes work, I am very thankful for it and I appreciate it a lot! I don't want to start a new Plug-In project wich is as you said mostly your code with some of my improvements and simplifications.... So please kindly accept my apologies - if I hurt your feelings, it was not my intention and today I will try to find the time to correct it and to upload it as a fork
> 
> I am rather interested in working together as a team having the common interest to make the project advance. I can also contribute helping implementing or testing new features. You said, we are behind the Mflux reseases implementing new features - please can you give a kind of a roadmap of implementing new features?
> 
> Also I propose to make a discord channel for this project, so we can have more direct communication. Again, I would like you to stay the main project leader and I dont wont to overtake this role, please forgive me any kind of impression that it was my intention.

I have felt your kindness, @InformEthics. Thank you, and I apologize once again for my previous reckless assumptions. I suggest that you keep your project. Just like this project is my first, I understand that feeling. Others may not value it, but at the very least, the author does. Personally, I even see it as my own child. Therefore, your project should be preserved, as it is your first project.

I’m also very glad that you have learned and made progress through this plugin. Yes, the current porting work is actually very basic. This method may simply be something others haven’t considered before, but I’ve always known about it. That’s because I once tried to port MLX's LLAMA into JOYCAPTION. Although it was based on MLX, it was successfully ported. Unfortunately, it didn’t function properly, and I even thought it wasn’t very intelligent. I didn’t explore further back then, but I did realize the possibility of running MLX in ComfyUI. Perhaps any Python program could run through ComfyUI.

That said, if we aim for more far-reaching goals, the current shallow-level porting is far from sufficient. This became especially clear to me during the process of porting mflux0.4.X. Other than the main feature of generating images, the rest of its functions are minor ones, but implementing these in ComfyUI is extremely challenging. It involves figuring out how to call ComfyUI’s UI components to control mflux. As a result, some breakdown and restructuring are necessary to make mflux and ComfyUI more seamlessly integrated. ComfyUI’s codebase is also much larger than mflux’s... I’m also exploring and experimenting step by step and encountering significant bottlenecks. Currently, real-time preview is in the final stages, but its implementation is far from perfect. It goes through all the steps in the QUICK node and displays all the images simultaneously. I believe there are still some steps that need fine-tuning. Perhaps once we overcome these challenges, this plugin could become a beginner-friendly template for learning how to port projects to ComfyUI, providing help to more people.

Team collaboration is a great idea, and I welcome you to join us! Just like @135kp suggested, we can work together to achieve some beautiful visions. His vision is very ambitious, and it actually aligns with my initial idea: to eventually integrate mflux into ComfyUI. This is a massive undertaking that will face many challenges, but I believe the key lies in data conversion—specifically, converting from PyTorch to MLX. Unfortunately, I currently know nothing about MLX and cannot devise a reasonable and specific roadmap. However, perhaps we can start by attempting the most basic breakdowns, such as latent variables. We could try to create a latent interface in the QUICK node and follow ComfyUI’s standard process to pass the latent variables into the image generation process. If we can achieve that, I’ll feel more confident about the subsequent work. This is also a consensus I reached with my friend @azrahello.

As for more direct communication, I can't think of any tools that would be more effective in conveying information. Actually, my English isn’t very good, so even with some instant messaging software, it would probably be hard to achieve efficiency, as I would still need translation. Perhaps we can try communicating directly here for now. I’ll open some threads to discuss the issues, and you can open them too. We can have a fully open and transparent discussion.

Also, this project is something I work on in my spare time, and I often don’t have enough time. Instant messaging would be of no use, and leaving comments here might have a similar effect.

I also saw the PR, and I think you’ve already tested it, so I can merge it directly. Thank you!

**Comment by raysers** [comment]
Hi, @135kp. You mentioned that you're a product manager, so I believe you're much more qualified than I am to handle project promotion. So far, I’ve done almost no promotion myself. The only thing I’ve done is post an answer on a Chinese Q&A platform, “Zhihu,” where I briefly mentioned this plugin. I think if we can move forward with team collaboration, we could consider doing some appropriate promotion. First, it might attract more contributors, and second, it would ensure our current efforts don’t go unnoticed.

If this plugin gains traction and reaches a wider audience, I could use its success to convince the MFlux official team of ComfyUI’s potential value as a strategic research tool. At that point, I would initiate another round of PR to request the official team’s involvement in this project. Of course, they are very busy, but at the very least, we could try to invite them to act as our advisors. This step would be critical for the next phase of research.

Your question in #9 made me realize how poorly written my current README is. It’s not beginner-friendly, and some features are not clearly explained. Perhaps you could help redesign a better-looking README? If you’re willing to take charge of this, I’d really look forward to it. I have only two additional requests:

1. It must be bilingual (Chinese and English), as my answer on Zhihu attracted a group of Chinese users, and the Chinese language cannot be overlooked.  
2. As in the current README, the acknowledgments section must come right after the title and introduction. I’m deeply grateful to the MFlux team and believe they deserve to be recognized first. Similarly, I’m also thankful to the author of MFLUX-WEBUI, who deserves equal appreciation.

This is the first improvement I can think of—starting with enhancing the README’s presentation. @135kp, I would greatly appreciate it if you’re willing to help. We can also discuss further steps afterward.

In the next couple of days, I’ll continue to think about team collaboration matters. I believe we can really start trying, as you mentioned, to leverage everyone’s strengths to advance this plugin.

P.S. For now, I’m posting this request here because everyone is present, ensuring it will be seen. Next time, I’ll create a new post for it.
